create table if not exists public.conversations (
  id bigint generated by default as identity primary key,
  buyer_id uuid not null references auth.users (id) on delete cascade,
  seller_id uuid not null references auth.users (id) on delete cascade,
  last_message text,
  last_message_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint conversations_buyer_seller_unique unique (buyer_id, seller_id),
  constraint conversations_buyer_not_seller check (buyer_id <> seller_id)
);

create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  conversation_id bigint not null references public.conversations (id) on delete cascade,
  sender_id uuid not null references auth.users (id) on delete cascade,
  receiver_id uuid not null references auth.users (id) on delete cascade,
  body text not null,
  created_at timestamptz not null default now(),
  read_at timestamptz,
  constraint messages_body_not_blank check (length(trim(body)) > 0),
  constraint messages_sender_not_receiver check (sender_id <> receiver_id)
);

create index if not exists conversations_buyer_id_idx
  on public.conversations (buyer_id);

create index if not exists conversations_seller_id_idx
  on public.conversations (seller_id);

create index if not exists conversations_last_message_at_idx
  on public.conversations (last_message_at desc nulls last);

create index if not exists messages_conversation_id_created_at_idx
  on public.messages (conversation_id, created_at);

create or replace function public.touch_conversation_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create or replace function public.sync_conversation_after_message()
returns trigger
language plpgsql
as $$
begin
  update public.conversations
  set
    last_message = new.body,
    last_message_at = new.created_at,
    updated_at = now()
  where id = new.conversation_id;

  return new;
end;
$$;

drop trigger if exists trg_touch_conversation_updated_at on public.conversations;
create trigger trg_touch_conversation_updated_at
before update on public.conversations
for each row
execute function public.touch_conversation_updated_at();

drop trigger if exists trg_sync_conversation_after_message on public.messages;
create trigger trg_sync_conversation_after_message
after insert on public.messages
for each row
execute function public.sync_conversation_after_message();

alter table public.conversations enable row level security;
alter table public.messages enable row level security;

drop policy if exists "Participants can view conversations" on public.conversations;
create policy "Participants can view conversations"
on public.conversations
for select
to authenticated
using (auth.uid() = buyer_id or auth.uid() = seller_id);

drop policy if exists "Buyer can create conversations" on public.conversations;
create policy "Buyer can create conversations"
on public.conversations
for insert
to authenticated
with check (auth.uid() = buyer_id);

drop policy if exists "Participants can update conversations" on public.conversations;
create policy "Participants can update conversations"
on public.conversations
for update
to authenticated
using (auth.uid() = buyer_id or auth.uid() = seller_id)
with check (auth.uid() = buyer_id or auth.uid() = seller_id);

drop policy if exists "Participants can view messages" on public.messages;
create policy "Participants can view messages"
on public.messages
for select
to authenticated
using (
  exists (
    select 1
    from public.conversations c
    where c.id = conversation_id
      and (auth.uid() = c.buyer_id or auth.uid() = c.seller_id)
  )
);

drop policy if exists "Participants can send messages" on public.messages;
create policy "Participants can send messages"
on public.messages
for insert
to authenticated
with check (
  auth.uid() = sender_id
  and exists (
    select 1
    from public.conversations c
    where c.id = conversation_id
      and (
        (c.buyer_id = sender_id and c.seller_id = receiver_id)
        or
        (c.seller_id = sender_id and c.buyer_id = receiver_id)
      )
  )
);

drop policy if exists "Participants can mark messages as read" on public.messages;
create policy "Participants can mark messages as read"
on public.messages
for update
to authenticated
using (
  exists (
    select 1
    from public.conversations c
    where c.id = conversation_id
      and (auth.uid() = c.buyer_id or auth.uid() = c.seller_id)
  )
)
with check (
  exists (
    select 1
    from public.conversations c
    where c.id = conversation_id
      and (auth.uid() = c.buyer_id or auth.uid() = c.seller_id)
  )
);
