-- 1. Create Escrow Confirmations table
CREATE TABLE IF NOT EXISTS public.escrow_confirmations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL REFERENCES public.orders(id) ON DELETE CASCADE,
    user_id UUID NOT NULL REFERENCES auth.users(id),
    role TEXT NOT NULL CHECK (role IN ('buyer', 'seller')),
    confirmed BOOLEAN DEFAULT FALSE,
    proof_image_url TEXT,
    confirmed_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(order_id, role)
);

-- 2. Enable RLS
ALTER TABLE public.escrow_confirmations ENABLE ROW LEVEL SECURITY;

-- 3. Policies for Escrow Confirmations
CREATE POLICY "Users can view own confirmations"
    ON public.escrow_confirmations FOR SELECT
    TO authenticated
    USING (auth.uid() = user_id);

CREATE POLICY "Users can insert own confirmations"
    ON public.escrow_confirmations FOR INSERT
    TO authenticated
    WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update own confirmations"
    ON public.escrow_confirmations FOR UPDATE
    TO authenticated
    USING (auth.uid() = user_id);

-- 4. Ensure orders have a status to support the escrow flow
-- (Most likely already exists, but ensure 'confirmed' or 'delivered' are possible)

-- 5. Add any missing columns to products if they aren't handled by JSONB
-- Note: The mobile app already uses 'listing_details' JSONB which is flexible.
-- However, we can add explicit columns for common filters if desired later.
